# Generated by Django 4.1.7 on 2023-04-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lottery",
            fields=[
                (
                    "lottery_id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True)),
                ("photo", models.ImageField(upload_to="photos/")),
                ("max_players", models.IntegerField()),
                ("gwei_fee", models.IntegerField()),
                ("address", models.CharField(blank=True, max_length=255)),
                ("creator_address", models.CharField(max_length=255)),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_end", models.DateTimeField()),
            ],
        ),
    ]
